### ISSUE TITLE
Reassign of const causes error

### ISSUE THREAD

**Issue by TKDBB84** [xivapi/XIV-Character-Cards#21]
Reassigning the `const response` when an error occur causes further errors:

https://github.com/xivapi/XIV-Character-Cards/blob/master/create-card.js#L304-L307

need to adjust to `let`

**Comment by ArcaneDisgea** [comment]
Heyo! Do you have an example character that I can reproduce this with?

**Comment by TKDBB84** [comment]
I think it happens randomly when there is a failure from the `fetch` call. But you can see from inspection that a variable declared as a `const` is being reassigned.

If you want to mock a server error you could mock fetch to return an error.  I can create a branch showing the error, and a PR to fix it if you'd like.

**Comment by ArcaneDisgea** [comment]
Yeah, if you didn't mind. I'm just curious what the error is and if we could prevent it. Changing to let doesn't seem to break anything so we can always change it anyways if we can't nail down the source of the error.

**Comment by ArcaneDisgea** [comment]
I was able to recreate the error, I believe. I'll change this to let and things should be good to go.
```json
{
"status": "error",
"reason": "createCard failed: TypeError: Assignment to constant variable."
}
```
