### ISSUE TITLE
Missing Reaper and Sage class job background images

### ISSUE THREAD

**Issue by Sollisnexus** [xivapi/XIV-Character-Cards#29]
Files for the background images for Reaper and Sage are missing so they direct currently to another available icon (Reaper -> Blue Mage)

**Comment by Sollisnexus** [comment]
![reaperisbluemageiguess](https://user-images.githubusercontent.com/44639933/145732143-8107b14c-9dd8-43bf-9509-6725f6b30c85.png)

Example (Not my character)

**Comment by ArcaneDisgea** [comment]
Forgot to close this issue. This has been resolved on the cards side, need to fix the xivapi side for it to actually work however.
